#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'largestSegment' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER_ARRAY radius
#  2. INTEGER segments
#

def splitCircle(area, segments):
    return area / segments

def largestSegment(radius, segments):
    # Write your code here
    pi = 3.14159265359

    #Sort and reverse radius
    radius.sort()
    radius.reverse()

    #Calculate areas and the total squared units
    areas = []
    areas_total = 0
    for i in radius:
        area = pi * i ** 2
        areas.append(area)
        areas_total += area

    largest_area = max(areas)

    j = 1
    for i in range(len(areas)):
    while  j <= 6:
        current_segmant = splitCircle(areas[i],j)

        j += 1

    print(largest_area)

    #Work on segments
    equal_segments = areas_total / segments
    print (equal_segments)

    return (str(round(largest_area, 4)))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    radius_count = int(input().strip())

    radius = []

    for _ in range(radius_count):
        radius_item = int(input().strip())
        radius.append(radius_item)

    segments = int(input().strip())

    result = largestSegment(radius, segments)

    fptr.write(result + '\n')

    fptr.close()
