#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'comparatorValue' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#  3. INTEGER d
#

def comparatorValue(a, b, d):
    # Write your code here
    b = list(set(b))

    comp_value = 0
    for i in a:
        inner_comp_value = 0
        for j in b:
            if abs(i - j) <= d:
                inner_comp_value += 1
                break
        if inner_comp_value == 0:
            comp_value += 1

    return comp_value


if __name__ == '__main__':
